services:
  - type: web
    name: docstyle-app
    plan: free
    runtime: node
    rootDir: backend
    buildCommand: npm install && cd ../frontend && npm install --legacy-peer-deps --include=dev && npm run build && cd ../backend && mkdir -p public && cp -r ../frontend/dist/. ./public
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
